import { IMessageData, IMessageDocument, MessageReactionType } from '@chat/interfaces/message.interface';
import { IConversationDocument, MessageType } from '@chat/interfaces/conversation.interface';
import { ConversationModel } from '@chat/models/conversation.schema';
import { MessageModel } from '@chat/models/message.schema';
import mongoose from 'mongoose';
import { NotAuthorizedError, NotFoundError } from '@global/helpers/error-handler';
import { deleteFromCloudinary } from '@global/helpers/cloudinary-upload';

class ChatService {
  public async addMessageToDB(data: IMessageData): Promise<IMessageData> {
    const { conversationId, senderId, receiverId } = data;
    const session = await mongoose.startSession();
    session.startTransaction();

    try {
      let conversation;

      // 1. First, try finding by ID if provided
      if (conversationId) {
        conversation = await ConversationModel.findById(conversationId).session(session);
      }

      // 2. IMPORTANT: If not found by ID (even if ID was provided),
      // we MUST check by participants before creating a new one.
      if (!conversation && receiverId) {
        conversation = await ConversationModel.findOne({
          participants: { $all: [senderId, receiverId], $size: 2 },
          isGroup: false
        }).session(session);
      }

      // 3. Only if still not found, create a new conversation
      if (!conversation) {
        if (!receiverId) throw new Error('ReceiverId is required for new conversations');

        const newConversation = new ConversationModel({
          // Use the ID generated by the controller to keep DB and Cache in sync
          _id: conversationId || new mongoose.Types.ObjectId(),
          participants: [senderId, receiverId],
          isGroup: false,
          unreadCounts: {
            [senderId.toString()]: 0,
            [receiverId.toString()]: 0
          }
        });
        conversation = await newConversation.save({ session });
      }

      // 4. Save the message using the identified/created conversation ID
      const [newMessage] = await MessageModel.create([{ ...data, conversationId: conversation._id }], { session });

      // 5. Update counts and last message metadata
      const incUpdate: Record<string, number> = { totalMessages: 1 };
      conversation.participants.forEach((id) => {
        if (id.toString() !== senderId.toString()) {
          incUpdate[`unreadCounts.${id}`] = 1;
        }
      });

      const lastMessagePreview = this.calculateLastMessagePreview(data.body, data.type);

      await ConversationModel.updateOne(
        { _id: conversation._id },
        {
          $set: {
            lastMessage: lastMessagePreview,
            lastMessageId: newMessage._id,
            lastMessageSenderId: senderId,
            lastMessageType: data.type,
            updatedAt: new Date()
          },
          $inc: incUpdate
        },
        { session }
      );

      await session.commitTransaction();
      return newMessage.toObject() as unknown as IMessageData;
    } catch (error) {
      await session.abortTransaction();
      throw error;
    } finally {
      session.endSession();
    }
  }

  public async getUserConversationList(userId: string): Promise<IConversationDocument[]> {
    const userObjectId = new mongoose.Types.ObjectId(userId);

    const conversations = await ConversationModel.aggregate([
      {
        $match: {
          participants: userObjectId
        }
      },
      {
        $lookup: {
          from: 'User',
          localField: 'participants',
          foreignField: '_id',
          as: 'participantsDocs'
        }
      },
      {
        $lookup: {
          from: 'Auth',
          localField: 'participantsDocs.authId',
          foreignField: '_id',
          as: 'authDocs'
        }
      },
      {
        $addFields: {
          participants: {
            $map: {
              input: '$participantsDocs',
              as: 'user',
              in: {
                _id: '$$user._id',
                profilePicture: '$$user.profilePicture',
                username: {
                  $let: {
                    vars: {
                      auth: {
                        $arrayElemAt: [
                          {
                            $filter: {
                              input: '$authDocs',
                              as: 'a',
                              cond: { $eq: ['$$a._id', '$$user.authId'] }
                            }
                          },
                          0
                        ]
                      }
                    },
                    in: '$$auth.username'
                  }
                },
                avatarColor: {
                  $let: {
                    vars: {
                      auth: {
                        $arrayElemAt: [
                          {
                            $filter: {
                              input: '$authDocs',
                              as: 'a',
                              cond: { $eq: ['$$a._id', '$$user.authId'] }
                            }
                          },
                          0
                        ]
                      }
                    },
                    in: '$$auth.avatarColor'
                  }
                }
              }
            }
          }
        }
      },
      {
        $project: {
          participantsDocs: 0,
          authDocs: 0
        }
      },
      { $sort: { updatedAt: -1 } }
    ]);

    return conversations;
  }

  public async getMessages(
    senderId: string,
    receiverId: string,
    conversationId: string | undefined,
    skip: number,
    limit: number = 25
  ): Promise<IMessageData[]> {
    let convIdObjectId: string;

    if (conversationId) {
      convIdObjectId = conversationId;
    } else {
      const conversation = await ConversationModel.findOne({
        participants: { $all: [senderId, receiverId], $size: 2 }
      });
      if (!conversation) return [];
      convIdObjectId = conversation._id.toString();
    }

    const messages = await MessageModel.find({
      conversationId: convIdObjectId,
      deletedFor: { $ne: senderId }
    })
      .select('-__v')
      .sort({ createdAt: -1 })
      .skip(skip)
      .limit(limit)
      .populate({
        path: 'replyTo',
        select: 'body type senderId _id'
      });

    return messages.reverse() as unknown as IMessageData[];
  }

  public async markMessageAsRead(readerId: string, conversationId: string, messageId: string): Promise<IConversationDocument | null> {
    const c = await ConversationModel.findOneAndUpdate(
      { _id: conversationId },
      {
        $set: {
          [`unreadCounts.${readerId}`]: 0,
          [`lastRead.${readerId}`]: messageId
        }
      },
      { new: true }
    );

    return c;
  }

  public async markMessageAsDelivered(userId: string, conversationId: string, messageId: string): Promise<void> {
    await ConversationModel.updateOne(
      { _id: conversationId },
      {
        $set: {
          [`lastDelivered.${userId}`]: messageId
        }
      }
    );
  }

  public async deleteMessage(messageId: string, senderId: string, type: 'me' | 'everyone'): Promise<IMessageDocument> {
    // 1. Delete for Me
    if (type === 'me') {
      const message = await MessageModel.findById(messageId);

      if (!message) throw new NotFoundError('Message Not Found.');

      const updatedMessage = await MessageModel.findByIdAndUpdate(messageId, { $push: { deletedFor: senderId } }, { new: true });
      return updatedMessage!;
    }

    // 2. Delete for Everyone
    else {
      const originalMessage = await MessageModel.findById(messageId);
      if (!originalMessage) throw new NotFoundError('Message not found');

      if (originalMessage.senderId.toString() !== senderId) {
        throw new NotAuthorizedError('Not authorized to delete this message');
      }

      if (originalMessage.selectedImage && originalMessage.selectedImage.length > 0) {
        const publicId = this.getPublicId(originalMessage.selectedImage);
        await deleteFromCloudinary(publicId, 'image');
      }

      if (originalMessage.selectedVideo && originalMessage.selectedVideo.length > 0) {
        const publicId = this.getPublicId(originalMessage.selectedVideo);
        await deleteFromCloudinary(publicId, 'video'); // Audio/Video often treat as 'video'
      }

      if (originalMessage.selectedAudio && originalMessage.selectedAudio.length > 0) {
        const publicId = this.getPublicId(originalMessage.selectedAudio);
        await deleteFromCloudinary(publicId, 'video');
      }

      const message = await MessageModel.findByIdAndUpdate(
        messageId,
        {
          isDeleted: true, // Flag so the front displays it in gray
          body: 'This message was deleted',
          selectedImage: '',
          selectedVideo: '',
          selectedAudio: '',
          gifUrl: '',
          replyTo: ''
        },
        { new: true }
      );

      const conversation = await ConversationModel.findById(message!.conversationId);
      if (conversation) {
        const isLastMessage = conversation.lastMessageId?.toString() === messageId;

        await ConversationModel.updateOne(
          { _id: conversation._id },
          {
            ...(isLastMessage && {
              $set: {
                lastMessage: 'This message was deleted',
                lastMessageType: 'text'
              }
            })
          }
        );
      }

      return message!;
    }
  }

  public async updateMessageReaction(messageId: string, senderId: string, reaction: MessageReactionType) {
    const senderObjectId = new mongoose.Types.ObjectId(senderId);

    const message = await MessageModel.findById(messageId);
    if (!message) throw new NotFoundError('Message not found');

    const hasReaction = message.reaction.find((r) => r.senderId.toString() === senderId);

    let updateQuery = {};
    let options: any = { new: true };

    if (hasReaction && hasReaction.type === reaction) {
      updateQuery = { $pull: { reaction: { senderId: senderObjectId } } };
    } else if (hasReaction) {
      updateQuery = { $set: { 'reaction.$[elem].type': reaction } };
      options.arrayFilters = [{ 'elem.senderId': senderObjectId }]; 
    } else {
      updateQuery = { $push: { reaction: { senderId: senderObjectId, type: reaction } } };
    }

    const updated = await MessageModel.findOneAndUpdate({ _id: messageId }, updateQuery, options);

    return updated;
  }

  private calculateLastMessagePreview = (body: string, type: string): string => {
    let lastMessagePreview = body; // Default (Text)

    if (!body) {
      if (type === MessageType.IMAGE) lastMessagePreview = '📷 Sent an image';
      if (type === MessageType.VIDEO) lastMessagePreview = '🎥 Sent a video';
      if (type === MessageType.AUDIO) lastMessagePreview = '🎤 Sent a voice note';
      if (type === MessageType.GIF) lastMessagePreview = '👾 Sent a GIF';
    } else {
      // If it's media and includes a caption, we can add a small tag.
      if (type === MessageType.IMAGE) lastMessagePreview = '📷 ' + body;
      if (type === MessageType.VIDEO) lastMessagePreview = '🎥 ' + body;
    }

    return lastMessagePreview;
  };

  private getPublicId(url: string): string {
    const splitUrl = url.split('/');
    return splitUrl[splitUrl.length - 1].split('.')[0];
  }
}

export const chatService: ChatService = new ChatService();
