import { uploadToCloudinary } from '@global/helpers/cloudinary-upload';
import { BadRequestError, joiRequestValidationError } from '@global/helpers/error-handler';
import { addImageSchema } from '@image/schemes/images';
import { UploadApiResponse } from 'cloudinary';
import { Request, Response } from 'express';
import { config } from '@root/config';
import { IUserDocument } from '@user/interfaces/user.interface';
import { UserCache } from '@service/redis/user.cache';
import { imageQueue } from '@service/queues/image.queue';
import HTTP_STATUS from 'http-status-codes';
import { userService } from '@service/db/user.service';
import { IBgUploadResponse } from '@image/interfaces/image.interface';
import { Helpers } from '@global/helpers/helpers';
import { socketIOUserObject } from '@socket/user';

const userCache: UserCache = new UserCache();

class Add {
  // =========================================================
  // 1. PROFILE IMAGE
  // =========================================================
  public profileImage = async (req: Request, res: Response): Promise<void> => {
    // A. Validation
    const { error, value } = addImageSchema.validate(req.body);
    if (error?.details) {
      throw new joiRequestValidationError(error.details[0].message);
    }

    // B. Upload Logic (New or Existing)
    const { image, existingPublicId, existingVersion } = value;
    // Helper handles both cases (New Base64 OR Existing Gallery ID)
    const { version, publicId, url } = await this.uploadImageHelper(image, existingPublicId, existingVersion);

    // C. Update Redis Cache ⚡
    let cachedUser: IUserDocument | null = (await userCache.updateUserItemsInCache(req.currentUser!.userId, {
      profilePicture: url
    })) as IUserDocument;

    // D. Fallback & Cache Repair 🛡️
    // If cache was empty/evicted, fetch from DB and Repair fully
    if (!cachedUser) {
      cachedUser = await this.repairUserCache(req.currentUser!.userId, { profilePicture: url });
    }

    // E. Socket Emit (Real-time Sync) 📡
    // Sending full user object ensures consistency across devices
    if (cachedUser) {
      socketIOUserObject.to(`user:${req.currentUser!.userId}`).emit('update user', cachedUser);
    }

    // F. DB Persistence (Queue) 💾
    imageQueue.addImageJob('addUserProfileImageToDB', {
      key: req.currentUser!.userId,
      value: url,
      publicId,
      version,
      newImage: image ? true : false
    });

    res.status(HTTP_STATUS.OK).json({ message: 'Profile image added successfully', url });
  };

  // =========================================================
  // 2. BACKGROUND IMAGE
  // =========================================================
  public backgroundImage = async (req: Request, res: Response): Promise<void> => {
    // A. Validation
    const { error, value } = addImageSchema.validate(req.body);
    if (error?.details) {
      throw new joiRequestValidationError(error.details[0].message);
    }

    // B. Upload Logic
    const { image, existingPublicId, existingVersion } = value;
    const { version, publicId, url } = await this.uploadImageHelper(image, existingPublicId, existingVersion);

    // C. Update Redis Cache ⚡
    // Update ID And Version
    let cachedUser: IUserDocument | null = (await userCache.updateUserItemsInCache(req.currentUser!.userId, {
      bgImageId: publicId,
      bgImageVersion: version
    })) as IUserDocument;

    // D. Fallback & Cache Repair 🛡️
    if (!cachedUser) {
      cachedUser = await this.repairUserCache(req.currentUser!.userId, {
        bgImageId: publicId,
        bgImageVersion: version
      });
    }

    // E. Socket Emit 📡
    if (cachedUser) {
      socketIOUserObject.to(`user:${req.currentUser!.userId}`).emit('update user', {
        ...cachedUser,
        bgImageUrl: url // Optional: helpful for frontend
      });
    }

    // F. DB Persistence (Queue) 💾
    imageQueue.addImageJob('addBackgroundImageToDB', {
      key: req.currentUser!.userId,
      publicId,
      version,
      newImage: image ? true : false
    });

    res.status(HTTP_STATUS.OK).json({ message: 'Background image added successfully', url });
  };

  // =========================================================
  // 🔒 PRIVATE HELPERS
  // =========================================================

  /**
   * General Helper for Uploads
   * Handles: New Base64 Upload OR Existing Gallery Reference
   */
  private uploadImageHelper = async (image: string, existingPublicId: string, existingVersion: string): Promise<IBgUploadResponse> => {
    const isBase64 = image ? Helpers.isBase64(image) : false;
    let version = '';
    let publicId = '';
    let url = '';

    if (isBase64) {
      // ✅ Case 1: New Image Upload (Unique ID generated by Cloudinary)
      const result: UploadApiResponse = await uploadToCloudinary(image, {
        overwrite: false, // Important for Gallery
        invalidate: true
      });

      version = result.version.toString();
      publicId = result.public_id;
      url = result.secure_url;
    } else {
      // ✅ Case 2: Using Existing Image from Gallery
      publicId = existingPublicId;
      version = existingVersion;
      url = `https://res.cloudinary.com/${config.CLOUD_NAME}/image/upload/v${version}/${publicId}`;
    }

    return { publicId, version, url };
  };

  /**
   * Cache Repair Strategy
   * Fetches from DB, Updates local fields, and Saves fully to Redis (ZADD + HSET)
   */
  private repairUserCache = async (userId: string, updates: Partial<IUserDocument>): Promise<IUserDocument | null> => {
    const userFromDb = await userService.getUserById(userId);
    if (!userFromDb) return null;

    // Update the fetched object with the new image data before caching
    for (const [key, value] of Object.entries(updates)) {
      // @ts-ignore
      userFromDb[key] = value;
    }

    // Full Save (ZADD + HSET) -> This is the "Repair" magic
    await userCache.saveUserToCache(`${userFromDb._id}`, `${userFromDb.uId}`, userFromDb);

    return userFromDb;
  };
}

export const add: Add = new Add();
